version: '3.3'

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME}-tg_bot-container"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}-tg_bot"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
    - ".env"
    networks:
    - tg_bot

  db:
    image: "postgres:14.5-alpine"
    container_name: "${BOT_CONTAINER_NAME}-db"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/data/pgdata"
    volumes:
    - ./pgdata:/var/data/pgdata
    env_file:
    - ".env"
    networks:
    - tg_bot


networks:
  tg_bot: